permalink: /:title

# Meta
title:                  Chris Canelake, Ed.D.
tagline:                Chris Canelake
aboutme:                
url:                    http://chris.canelake.com
baseurl:                http://chris.canelake.com/
author:
  name:                 Sarina Canelake
  url:                  https://www.linkedin.com/in/sarinac/
  email:                sarina@canelake.com

# Custom vars

