permalink: /:title

# Meta
title:                  Chris Canelake, Ed.D.
tagline:                Chris Canelake
aboutme:                
url:                    http://chris.canelake.com
baseurl:                /
author:
  name:                 Chris Canelake
  url:                  https://www.linkedin.com/in/chris-canelake-ed-d-1b74aa5/
  email:                chris@canelake.com

# Custom vars

